### ISSUE TITLE
The avatar cannot be loaded in your blog web page

### ISSUE THREAD

**Issue by yuanboliu** [RaulWei/RaulWei.github.io#1]
See the pic as below:
![selection_138](https://cloud.githubusercontent.com/assets/5643344/26041224/cda35bb2-38f0-11e7-9878-d4fcd2e033e4.png)

**Comment by RaulWei** [comment]
@yuanboliu Sometimes it appears if you refresh for several times.
Maybe the pic server is not stable enough. Anyway, I'll change another avatar.

**Comment by yuanboliu** [comment]
You can try this command when you commit to fix the issue:
git commit -m "#1 blablabla".
Then the commit will be attached to #1 issue.
